definitions:
  ApiError:
    properties:
      error:
        example: Validation error
        type: string
    type: object
  Clasroom:
    properties:
      desc:
        example: 25 | Филиалы Челябинский филиал | Лекционная
        type: string
      id:
        example: "3587"
        type: string
      title:
        example: "24"
        type: string
    type: object
  Group:
    properties:
      desc:
        example: Финансовый факультет | Очная
        type: string
      id:
        example: "110694"
        type: string
      title:
        example: ФФ21-1
        type: string
    type: object
  LoginRequest:
    properties:
      password:
        example: Bibt8877
        type: string
      username:
        example: "227789"
        type: string
    required:
    - password
    - username
    type: object
  LoginResponse:
    properties:
      token:
        example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
    type: object
  Teacher:
    properties:
      desc:
        example: Департамент гуманитарных наук
        type: string
      id:
        example: 00000000-0001-2345-6789-000000005451
        type: string
      title:
        example: Махаматов Таир
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5051/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      description: In success case returns Access JWT Token
      parameters:
      - description: Credentials input
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/LoginResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiError'
      summary: Try to sign in user
      tags:
      - auth
  /classrooms/:
    get:
      description: Return list of classrooms which found by provided query term
      parameters:
      - description: Classroom search mask
        in: query
        name: term
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Clasroom'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiError'
      summary: Return List of classrooms
      tags:
      - classrooms
  /groups/:
    get:
      description: Return list of student groups which found by provided query term
      parameters:
      - description: Group search mask
        in: query
        name: term
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Group'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiError'
      summary: Return List of groups
      tags:
      - groups
  /teachers/:
    get:
      description: Return list of teachers which found by provided query term
      parameters:
      - description: Teacher search mask
        in: query
        name: term
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Teacher'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ApiError'
      summary: Return List of teachers
      tags:
      - teachers
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
