basePath: /
definitions:
  orgfaclient.GetMiniProfileInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.GetMyGroupInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.GetOrderInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.GetProfileInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.GetRecordBookInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.GetStudentCardInput:
    properties:
      profileId:
        type: string
      sessionId:
        type: string
    type: object
  orgfaclient.GetStudyPlanInput:
    properties:
      sessionId:
        type: string
    type: object
  orgfaclient.LoginInput:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  ruzfaclient.GetAuditoriumInput:
    properties:
      auditorium:
        type: string
    type: object
  ruzfaclient.GetAuditoriumScheduleInput:
    properties:
      auditoriumId:
        type: string
      endDate:
        type: string
      startDate:
        type: string
    type: object
  ruzfaclient.GetGroupScheduleInput:
    properties:
      endDate:
        type: string
      groupId:
        type: string
      startDate:
        type: string
    type: object
  ruzfaclient.GetGroupsInput:
    properties:
      group:
        type: string
    type: object
  ruzfaclient.GetTeacherInput:
    properties:
      teacher:
        type: string
    type: object
  ruzfaclient.GetTeacherScheduleInput:
    properties:
      endDate:
        type: string
      startDate:
        type: string
      teacherId:
        type: string
    type: object
host: localhost:5555
info:
  contact: {}
  title: Finapp-api
paths:
  /finapp/api/auditorium:
    post:
      consumes:
      - application/json
      description: get auditorium
      parameters:
      - description: auditorium info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetAuditoriumInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetAuditorium
      tags:
      - TimeTable
  /finapp/api/auditorium/schedule:
    post:
      consumes:
      - application/json
      description: get auditorium schedule
      parameters:
      - description: auditorium schedule info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetAuditoriumScheduleInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetAuditoriumSchedule
      tags:
      - TimeTable
  /finapp/api/auth:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: auth
      parameters:
      - description: auth
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.LoginInput'
      produces:
      - application/x-www-form-urlencoded
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Auth
      tags:
      - OrgFaRu
  /finapp/api/auth/miniprofile:
    get:
      consumes:
      - application/json
      description: GetMiniProfile
      parameters:
      - description: Get mini profile info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetMiniProfileInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetMiniProfile
      tags:
      - OrgFaRu
  /finapp/api/auth/miniprofile/profile:
    get:
      consumes:
      - application/json
      description: GetProfile
      parameters:
      - description: Profile info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetProfileInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetProfile
      tags:
      - OrgFaRu
  /finapp/api/auth/miniprofile/profile/order:
    get:
      consumes:
      - application/json
      description: GetOrder
      parameters:
      - description: Order info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetOrderInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetOrder
      tags:
      - OrgFaRu
  /finapp/api/auth/miniprofile/profile/studentcard:
    get:
      consumes:
      - application/json
      description: GetStudentCard
      parameters:
      - description: Get student card info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetStudentCardInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetStudentCard
      tags:
      - OrgFaRu
  /finapp/api/auth/miniprofile/profile/studyplan/{profileId}:
    get:
      consumes:
      - application/json
      description: GetStudyPlan
      parameters:
      - description: Get study plan info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetStudyPlanInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetStudyPlan
      tags:
      - OrgFaRu
  /finapp/api/auth/mygroup:
    get:
      consumes:
      - application/json
      description: get myGroup
      parameters:
      - description: myGroup info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetMyGroupInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetMyGroup
      tags:
      - OrgFaRu
  /finapp/api/auth/recordbook:
    get:
      consumes:
      - application/json
      description: get GetRecordBook
      parameters:
      - description: Record book info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/orgfaclient.GetRecordBookInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetRecordBook
      tags:
      - OrgFaRu
  /finapp/api/group:
    post:
      consumes:
      - application/json
      description: get group
      parameters:
      - description: group info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetGroupsInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetGroup
      tags:
      - TimeTable
  /finapp/api/group/schedule:
    post:
      consumes:
      - application/json
      description: get groupSchedule
      parameters:
      - description: group schedule info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetGroupScheduleInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetGroupSchedule
      tags:
      - TimeTable
  /finapp/api/teacher:
    post:
      consumes:
      - application/json
      description: get teacher
      parameters:
      - description: teacher info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetTeacherInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetTeacher
      tags:
      - TimeTable
  /finapp/api/teacher/schedule:
    post:
      consumes:
      - application/json
      description: get teacherSchedule
      parameters:
      - description: teacher schedule info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ruzfaclient.GetTeacherScheduleInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: GetTeacherSchedule
      tags:
      - TimeTable
swagger: "2.0"
